52 event controller
ESGI-69/challenge-stack pull request #104
Opened 2023-02-06 22:29 UTC by ycenta

2023-02-06 22:36 UTC, Timdev0 requested changes

2023-02-06 22:36 UTC, Timdev0 commented on src/Entity/Event.php
> +    #[Slug(fields: ['title'])]
peut etre mettre ['title', 'id'] pour que ce soit unique

2023-02-06 23:45 UTC, ycenta commented on src/Entity/Event.php
> +    #[Slug(fields: ['title'])]
pas bête

2023-02-07 09:48 UTC, mrpinkcat requested changes

2023-02-07 09:48 UTC, mrpinkcat commented on templates/Front/event/show.html.twig
> +
Utilise un component twig. Comme dans la maquette.

<img width="888" alt="Capture d’écran 2023-02-07 à 10 45 29" src="https://user-images.githubusercontent.com/13932200/217209570-6ac4955b-d68b-45a0-b213-458f563e9a6a.png">

Si tu penses pas pouvoir le faire c'est pas grave mais utilise au moins un component twig pour le media ;)

2023-02-07 09:54 UTC, mrpinkcat commented on templates/Front/event/show.html.twig
> +
(à droite)

2023-02-08 01:30 UTC, mrpinkcat approved these changes

2023-02-08 09:05 UTC, Timdev0 approved these changes

2023-02-08 09:05 UTC, merged